# Site settings
title: Distributed thoughts on everything software
description: Distributed thoughts on everything software
author: Ashish Sharma
email: a-sharma@outlook.com
url: "https://a-sharma11.github.io" # Your GitHub Pages URL
baseurl: "/blogposts" # Repository name (use "" if repository is username.github.io)

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .well-known

